<a href="https://colab.research.google.com/github/snwnkang/CS171_Final_vis_Marathon/blob/main/combine_data_chicago.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
from bs4 import BeautifulSoup
import requests
import json
from IPython.display import HTML
import html

In [5]:
chicago2014 = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/chicago_data/Chicago_Marathon2014.csv")
chicago2015 = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/chicago_data/Chicago_Marathon2015.csv")
chicago2016 = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/chicago_data/Chicago_Marathon2016.csv")
chicago2017 = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/chicago_data/Chicago_Marathon2017.csv")
chicago2018 = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/chicago_data/Chicago_Marathon2018.csv")
chicago2019 = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/chicago_data/Chicago_Marathon2019.csv")
chicago2021 = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/chicago_data/Chicago_Marathon2021.csv")
chicago2022 = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/chicago_data/Chicago_Marathon2022.csv")
chicago2023 = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/chicago_data/Chicago_Marathon2023.csv")

In [6]:
chicago2022

,Last Name,First Name,Division,Country,BIB,Overall Place,Time,seconds,Year,Gender
0,Kipruto,Benson,30-34,KEN,9,1,02:04:24,7464.0,2022,M
1,Tura Abdiwak,Seifu,25-29,ETH,1,2,02:04:49,7489.0,2022,M
2,Korir,John,25-29,KEN,21,3,02:05:01,7501.0,2022,M
3,Koech,Bernard,30-34,KEN,3,4,02:07:15,7635.0,2022,M
4,Tamru Aredo,Shifera,20-24,ETH,10,5,02:07:53,7673.0,2022,M
...,...,...,...,...,...,...,...,...,...,...
295,Hofmann,Eric,35-39,USA,553,296,02:37:39,9459.0,2022,M
296,Garbier,James,25-29,USA,8104,297,02:37:40,9460.0,2022,M
297,Marroquin Gonzalez,Ricardo,30-34,MEX,3055,298,02:37:40,9460.0,2022,M
298,Zeha,Jeffery,40-44,USA,532,299,02:37:41,9461.0,2022,M
299,Vogl,Dominic,35-39,USA,3550,300,02:37:41,9461.0,2022,M

In [7]:
combined_chicago = pd.concat(
    [chicago2014, chicago2015, chicago2016, chicago2017, chicago2018, chicago2019, chicago2021, chicago2022, chicago2023],
    ignore_index=True
)

In [8]:
combined_chicago

,Last Name,First Name,Division,Country,BIB,Overall Place,Time,seconds,Year,Gender
0,Kipchoge,Eliud,25-29,KEN,2,1,02:04:11,7451.0,2014,M
1,Kitwara,Sammy,25-29,KEN,6,2,02:04:28,7468.0,2014,M
2,Chumba,Dickson,25-29,KEN,7,3,02:04:32,7472.0,2014,M
3,Bekele,Kenenisa,30-34,ETH,1,4,02:05:51,7551.0,2014,M
4,Koech,Bernard,25-29,KEN,5,5,02:08:30,7710.0,2014,M
...,...,...,...,...,...,...,...,...,...,...
2695,Rolon,Guillermo,45-49,MEX,18008,296,2:34:51,9291.0,2023,M
2696,Liepins,Kristaps,25-29,LAT,3134,297,2:34:54,9294.0,2023,M
2697,Teter,Joey,30-34,USA,777,298,2:34:56,9296.0,2023,M
2698,Foley,Vivian,50-54,IRL,25211,299,2:34:57,9297.0,2023,M
2699,Rohan,Carson,20-24,USA,8047,300,2:34:57,9297.0,2023,M

In [9]:
combined_chicago.to_csv("combined_Chicago_data.csv", index=False)

In [10]:
combined_chicago['marathon'] = "Chicago"

In [11]:
combined_chicago

,Last Name,First Name,Division,Country,BIB,Overall Place,Time,seconds,Year,Gender,marathon
0,Kipchoge,Eliud,25-29,KEN,2,1,02:04:11,7451.0,2014,M,Chicago
1,Kitwara,Sammy,25-29,KEN,6,2,02:04:28,7468.0,2014,M,Chicago
2,Chumba,Dickson,25-29,KEN,7,3,02:04:32,7472.0,2014,M,Chicago
3,Bekele,Kenenisa,30-34,ETH,1,4,02:05:51,7551.0,2014,M,Chicago
4,Koech,Bernard,25-29,KEN,5,5,02:08:30,7710.0,2014,M,Chicago
...,...,...,...,...,...,...,...,...,...,...,...
2695,Rolon,Guillermo,45-49,MEX,18008,296,2:34:51,9291.0,2023,M,Chicago
2696,Liepins,Kristaps,25-29,LAT,3134,297,2:34:54,9294.0,2023,M,Chicago
2697,Teter,Joey,30-34,USA,777,298,2:34:56,9296.0,2023,M,Chicago
2698,Foley,Vivian,50-54,IRL,25211,299,2:34:57,9297.0,2023,M,Chicago
2699,Rohan,Carson,20-24,USA,8047,300,2:34:57,9297.0,2023,M,Chicago

In [12]:
combined_chicago.to_csv("combined_Chicago_data.csv", index=False)