<a href="https://colab.research.google.com/github/snwnkang/CS171_Final_vis_Marathon/blob/main/ny_marathon_compiler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [5]:
nydf2014 = pd.read_csv('https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/nymarathon_data/NY_Marathon2014.csv')
nydf2015 = pd.read_csv('https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/nymarathon_data/NY_Marathon2015.csv')
nydf2016 = pd.read_csv('https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/nymarathon_data/NY_Marathon2016.csv')
nydf2017 = pd.read_csv('https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/nymarathon_data/NY_Marathon2017.csv')
nydf2018 = pd.read_csv('https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/nymarathon_data/NY_Marathon2018.csv')
nydf2019 = pd.read_csv('https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/nymarathon_data/NY_Marathon2019.csv')
nydf2020 = pd.read_csv('https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/nymarathon_data/NY_Marathon2020.csv')
nydf2021 = pd.read_csv('https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/nymarathon_data/NY_Marathon2021.csv')
nydf2022 = pd.read_csv('https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/nymarathon_data/NY_Marathon2022.csv')
nydf2023 = pd.read_csv('https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/nymarathon_data/NY_Marathon2023.csv')

In [9]:
#add a year column to all of them
nydf2014['Year'] = 2014
nydf2015['Year'] = 2015
nydf2016['Year'] = 2016
nydf2017['Year'] = 2017
nydf2018['Year'] = 2018
nydf2019['Year'] = 2019
nydf2020['Year'] = 2020
nydf2021['Year'] = 2021
nydf2022['Year'] = 2022
nydf2023['Year'] = 2023

In [11]:
nydf_combined = pd.concat([
    nydf2014, nydf2015, nydf2016, nydf2017, nydf2018,
    nydf2019, nydf2020, nydf2021, nydf2022, nydf2023
], ignore_index=True)

In [12]:
nydf_combined

,Name,Gender,Age,Country,BIB,Overall Place,Time,Year
0,Wilson Kipsang,M,32,KEN,2,1,2:10:59,2014
1,Lelisa Desisa Benti,M,24,ETH,4,2,2:11:06,2014
2,Gebre Gebremariam,M,30,ETH,7,3,2:12:13,2014
3,Meb Keflezighi,M,39,USA,5,4,2:13:18,2014
4,Stephen Kiprotich,M,25,UGA,11,5,2:13:25,2014
...,...,...,...,...,...,...,...,...
3055,Kevin Jennings,M,29,USA,2766,302,2:45:10,2023
3056,Connor Hesselbirg,M,28,USA,7579,303,2:45:12,2023
3057,Charlie Osmond,M,46,GBR,1550,304,2:45:13,2023
3058,Manuel Haberer,M,33,ITA,2064,305,2:45:15,2023
3059,Richard Marriott,M,43,GBR,1478,306,2:45:16,2023

In [13]:
nydf_combined.to_csv('NY_Marathon_Combined.csv', index=False)