<a href="https://colab.research.google.com/github/snwnkang/CS171_Final_vis_Marathon/blob/main/London_Marathon_scraper_inprogress.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
from bs4 import BeautifulSoup
import requests
import json
from IPython.display import HTML
import html

In [9]:
year = 2017
gender = 'F'

In [3]:
raw_html = """<html><head><style>body {transition: opacity ease-in 0.2s; }
body[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; }
</style>
<title>Virgin Money London Marathon 2018</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="stylesheet" href="//results-static.mikatiming.com/stages/blue/lib/static/bootstrap-3.3.7/css/bootstrap.css">
<link rel="stylesheet" href="//results-static.mikatiming.com/stages/blue/lib/static/styles.build/custom/bootstrap-theme.css">
<link rel="stylesheet" href="//results-static.mikatiming.com/stages/blue/lib/static/styles.build/custom/style.css">
<link href="/2018/?content=css_event&amp;theme=default&amp;event=2018_london&amp;style=custom" rel="stylesheet" type="text/css">
<link rel="shortcut icon" href="//results-static.mikatiming.com/stages/blue/images/favicon.ico">
<script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/js?id=G-X7BG41Z7K0&amp;l=dataLayer&amp;cx=c"></script><script type="text/javascript" src="//assets.mikatiming.com/lib/jquery/1.11.3/jquery.min.js"></script>
<script src="//results-static.mikatiming.com/stages/blue/lib/static/bootstrap-3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/2018/?content=ajax2&amp;client=js"></script>
<script type="text/javascript"> var require = {"baseUrl":"\/\/results-static.mikatiming.com\/stages\/blue\/lib\/static","deps":["\/\/results-static.mikatiming.com\/stages\/blue\/lib\/static\/webcomponentsjs-0.7.0\/webcomponents-lite.js"],"paths":{"d3":"d3-3.4.13\/d3","c3":"c3-0.4.8\/c3","moment":"moment.js-2.9.0\/moment-with-locales.min","GDouglasPeuker":"GDouglasPeuker","Mika":"Mika.build","async":"require.js-plugins-1.0.3\/async","combokeys":"combokeys-2.3.0\/dist\/combokeys","videojs":"..\/..\/node_modules\/video.js\/dist\/video.min","hls2":"videojs5-hlsjs-source-handler\/dist\/videojs5-hlsjs-source-handler","nouislider":"noUiSlider-9.2.0\/nouislider.min","screenfull":"screenfull.js-4.0.0\/screenfull","lodashIsEqual":"lodash\/isEqual","Mika\/Cookie":"Mika.build\/Cookie.js?ff716e5556","Mika\/Dialog":"Mika.build\/Dialog.js?c4ce14ed92","Mika\/Environment":"Mika.build\/Environment.js?c29942fcfd","Mika\/FavoriteColorMapper":"Mika.build\/FavoriteColorMapper.js?c9630670ac","Mika\/ImageErrorHandler":"Mika.build\/ImageErrorHandler.js?ee9286242b","Mika\/ImageViewer":"Mika.build\/ImageViewer.js?c06c87b4c1","Mika\/Logger":"Mika.build\/Logger.js?e1107568f4","Mika\/Map\/FavoriteBar":"Mika.build\/Map\/FavoriteBar.js?3ea7f5c014","Mika\/Map\/LatLng":"Mika.build\/Map\/LatLng.js?52354fc88e","Mika\/Map\/LatLngBounds":"Mika.build\/Map\/LatLngBounds.js?1dfacf85e0","Mika\/Map\/Map":"Mika.build\/Map\/Map.js?4f877dc9d8","Mika\/Map\/Marker\/Cluster\/Cluster":"Mika.build\/Map\/Marker\/Cluster\/Cluster.js?9d663798b5","Mika\/Map\/Marker\/Cluster\/Icon":"Mika.build\/Map\/Marker\/Cluster\/Icon.js?760db97eac","Mika\/Map\/Marker\/Cluster\/MarkerCluster":"Mika.build\/Map\/Marker\/Cluster\/MarkerCluster.js?74facae188","Mika\/Map\/Marker\/CollisionSupressor":"Mika.build\/Map\/Marker\/CollisionSupressor.js?c4ce53292e","Mika\/Map\/Marker\/CustomImage":"Mika.build\/Map\/Marker\/CustomImage.js?388a6d995f","Mika\/Map\/Marker\/Flag":"Mika.build\/Map\/Marker\/Flag.js?a07e8bf012","Mika\/Map\/Marker\/Icons":"Mika.build\/Map\/Marker\/Icons.js?f82b755835","Mika\/Map\/Marker\/Km":"Mika.build\/Map\/Marker\/Km.js?82e293c641","Mika\/Map\/Marker\/Overlay":"Mika.build\/Map\/Marker\/Overlay.js?ae15904211","Mika\/Map\/Marker\/OverlayImage":"Mika.build\/Map\/Marker\/OverlayImage.js?243c09e42c","Mika\/Map\/Marker\/Person":"Mika.build\/Map\/Marker\/Person.js?ffeb0b2784","Mika\/Map\/Object\/Circle":"Mika.build\/Map\/Object\/Circle.js?05cd4972be","Mika\/Map\/Polyline":"Mika.build\/Map\/Polyline.js?c5c43f51bc","Mika\/Mika":"Mika.build\/Mika.js?71f1195427","Mika\/PolylineEditor":"Mika.build\/PolylineEditor.js?72eb0e6511","Mika\/Popover":"Mika.build\/Popover.js?4e7d1c290d","Mika\/Quicksearch":"Mika.build\/Quicksearch.js?c0b9e8b89a","Mika\/Results\/Board":"Mika.build\/Results\/Board.js?fba8687d7c","Mika\/Results\/Plugins\/favorite_display":"Mika.build\/Results\/Plugins\/favorite_display.js?66d3b96320","Mika\/Results\/Plugins\/favorites":"Mika.build\/Results\/Plugins\/favorites.js?59d7f710e3","Mika\/Results\/Plugins\/global_option_bar":"Mika.build\/Results\/Plugins\/global_option_bar.js?6d60242b49","Mika\/Results\/Plugins\/graph":"Mika.build\/Results\/Plugins\/graph.js?34677aebe4","Mika\/Results\/Plugins\/list":"Mika.build\/Results\/Plugins\/list.js?75427b6c42","Mika\/Results\/Plugins\/list_responsive":"Mika.build\/Results\/Plugins\/list_responsive.js?b4bfd71e0b","Mika\/Results\/Plugins\/main_buttons":"Mika.build\/Results\/Plugins\/main_buttons.js?730f1cd329","Mika\/Results\/Plugins\/map":"Mika.build\/Results\/Plugins\/map.js?94097b963a","Mika\/Results\/Plugins\/overlays":"Mika.build\/Results\/Plugins\/overlays.js?2fb2b0d457","Mika\/Results\/Plugins\/pacegraph":"Mika.build\/Results\/Plugins\/pacegraph.js?d5a298929c","Mika\/Results\/Plugins\/race_flow_table":"Mika.build\/Results\/Plugins\/race_flow_table.js?b1a49d7944","Mika\/Results\/Plugins\/remote_content":"Mika.build\/Results\/Plugins\/remote_content.js?66ab0ba871","Mika\/Results\/Plugins\/strings":"Mika.build\/Results\/Plugins\/strings.js?be3574f716","Mika\/Results\/Requester":"Mika.build\/Results\/Requester.js?e08e2c3a1b","Mika\/SearchProvider":"Mika.build\/SearchProvider.js?119e90ba1f","Mika\/Sharer\/Networks\/base":"Mika.build\/Sharer\/Networks\/base.js?5e512e5688","Mika\/Sharer\/Networks\/facebook":"Mika.build\/Sharer\/Networks\/facebook.js?0d6fa0375a","Mika\/Sharer\/Networks\/googleplus":"Mika.build\/Sharer\/Networks\/googleplus.js?3beb6aba2b","Mika\/Sharer\/Networks\/twitter":"Mika.build\/Sharer\/Networks\/twitter.js?aa24183cf7","Mika\/Sharer\/Networks\/whatsapp":"Mika.build\/Sharer\/Networks\/whatsapp.js?4033c2aa8c","Mika\/Sharer\/Networks\/xing":"Mika.build\/Sharer\/Networks\/xing.js?39187fc831","Mika\/Sharer\/Sharer":"Mika.build\/Sharer\/Sharer.js?c7dcac3a10","Mika\/Ticker":"Mika.build\/Ticker.js?141ff57f2e","Mika\/Timer":"Mika.build\/Timer.js?260b39f15c","Mika\/Tools":"Mika.build\/Tools.js?370394a8e7","Mika\/Tracker":"Mika.build\/Tracker.js?e68c5b2784","Mika\/Uploader":"Mika.build\/Uploader.js?68ac256df1","Mika\/VideoViewer":"Mika.build\/VideoViewer.js?7dbe05ea75"},"config":{"Mika\/Mika":{"debug":false,"display_errors":true,"pathIcons":"\/\/assets.mikatiming.com\/img\/mt\/results\/default","language":"EN_CAP","global_event_id":"2018_london","static_uri":"\/\/results-static.mikatiming.com\/stages\/blue"},"Mika\/Logger":{"debug":false},"Mika\/Quicksearch":{"pid":null,"not_found_string":"Sorry, no results found!"},"Mika\/ImageViewer":{"pathIcons":"\/\/assets.mikatiming.com\/img\/mt\/results\/default","sharerActive":false},"Mika\/VideoViewer":{"pathIcons":"\/\/assets.mikatiming.com\/img\/mt\/results\/default","modalWidth":null},"Mika\/Map\/Map":{"mapProvider":"here"},"Mika\/Sharer\/Sharer":{"pathSharerIcons":"\/\/assets.mikatiming.com\/img\/mt\/sharer\/","buttonSize":"xs"},"Mika\/Map\/Marker\/Person":[]}}</script>
<script type="text/javascript" src="//results-static.mikatiming.com/stages/blue/lib/static/require.js-2.3.6/require.min.js"></script>
<script type="text/javascript" src="//results-static.mikatiming.com/stages/blue/lib/static/Emitter.js"></script>
<meta name="apple-mobile-web-app-capable" content="yes">
<script type="text/javascript">
        // create helper function to handle the image loading errors
        var mikaImageErrorHandler = function (image) {
            require(["Mika/ImageErrorHandler"], function (ImageErrorHandler) {
                var que = ImageErrorHandler.queueImageGeneration(image.dataset.generateSrcUrl, image.dataset.imageHash, image.src);
                setTimeout(function () {
                     ImageErrorHandler.statusMissingImages(que);
                }, 1100);
            })
        };
        require(["Mika/Mika", "require"], function (Mika, require) {
            new Mika();
            require(["Mika/Dialog", "Mika/Popover", "Mika/ImageViewer", "Mika/Timer"]);
        });
    </script>
<script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="//results-static.mikatiming.com/stages/blue/lib/static/webcomponentsjs-0.7.0/webcomponents-lite.js" src="//results-static.mikatiming.com/stages/blue/lib/static/webcomponentsjs-0.7.0/webcomponents-lite.js"></script><script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="Mika/Mika" src="//results-static.mikatiming.com/stages/blue/lib/static/Mika.build/Mika.js?71f1195427"></script><script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="Mika/Tracker" src="//results-static.mikatiming.com/stages/blue/lib/static/Mika.build/Tracker.js?e68c5b2784"></script><script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="Mika/Logger" src="//results-static.mikatiming.com/stages/blue/lib/static/Mika.build/Logger.js?e1107568f4"></script><script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="Mika/Tools" src="//results-static.mikatiming.com/stages/blue/lib/static/Mika.build/Tools.js?370394a8e7"></script><script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="Mika/Map/LatLng" src="//results-static.mikatiming.com/stages/blue/lib/static/Mika.build/Map/LatLng.js?52354fc88e"></script><script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="Mika/Sharer/Sharer" src="//results-static.mikatiming.com/stages/blue/lib/static/Mika.build/Sharer/Sharer.js?c7dcac3a10"></script><script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="Mika/Quicksearch" src="//results-static.mikatiming.com/stages/blue/lib/static/Mika.build/Quicksearch.js?c0b9e8b89a"></script></head>
<body class="pid-list content-list view-public branch-production site-2018_london event-MAS">

<div class="top-box bg pid-list" id="top-box-bg">
 <div class="topnav"></div><div class="bg-image"></div>
</div>


<div id="main" class="main">
<div class="head">
<div class="head-content">
<div class="nav"><a href="/2018/">
<img class="logo-screen" src="//results-static.mikatiming.com/2018/london/../london/styles/custom/logo.png" alt="">
</a></div>
</div>
</div>
<!-- header end -->
<!-- main start -->
<script async="" src="https://www.googletagmanager.com/gtag/js"></script>

        <script>

         var mt_tracker = {};

         window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            require(['Mika/Tracker'], function(tracker) {
                tracker.setGtagConfig(["G-X7BG41Z7K0"], {"page_title":"list","send_page_view":false,"meeting_id":"9999990F5ECC85000000016C","meeting_name":"Virgin Money London Marathon 2018","meeting_year":"2018","results_view":"public"});
                tracker.track('page_view');
                mt_tracker = tracker;
            });

    </script>
        <div id="main-content">
<div class="content">
<div class="results">
<div class="cbox head-links pid-list" id="cbox-head-links">
<!-- cbox content start -->

             <a href="http://www.virginmoneylondonmarathon.com">&gt; www.virginmoneylondonmarathon.com</a> <a class="button-minimarathon" href="minimarathon/">&gt; minimarathon</a>

<!-- cbox content end -->
</div>


<div class="cbox headline pid-list" id="cbox-headline">
<!-- cbox content start -->

             <a href="#">Virgin Money London Marathon</a> <a class="subline" href="#/">Tracking &amp; Results 2018</a>

<!-- cbox content end -->
</div>


<div class="cbox left pid-list" id="cbox-left">
<!-- cbox include start -->
<div class="menu">
<a class="active nav-pid-start" href="/2018/?event=MAS&amp;num_results=100&amp;pid=start&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W"><span>Search Results</span></a><a class="nav-pid-leaderboard" href="/2018/?pid=leaderboard"><span>Leaderboard</span></a><a class="nav-pid-tracking" href="/2018/?pid=tracking"><span>Tracking</span></a><a class="nav-pid-favorites" href="/2018/?pid=favorites"><span>My Runners</span></a></div><!-- menu end -->
        <div class="backgr-top"></div>
        <div class="backgr-bottom"></div>
        <div class="cbox-head">Virgin Money London Marathon 2018</div>
                <div class="cbox-content">
        <div class="list">
<div class="list-head"> Results: Club, Charity and Ballot
</div>

<div class="list-info">
<div class="list-info-text">
16418 Results | unofficial results | <span class="sex">Women</span>
</div>
<div style="clear:both"></div>
</div>
<table class="list-table">
<thead>
<tr>
  <th title="" style="width:50px;"> Place overall</th>
  <th title="" style="width:50px;"> Place gender</th>
  <th title="" style="width:50px;"> Place cat.</th>
  <th title="" style="width:;">Name

  </th>
  <th title="" style="width:150px;"> Club</th>
  <th title="" style="width:50px;"> Runner no</th>
  <th title="" style="width:70px;"> Category</th>
  <th title="" style="width:;"> Half</th>
  <th title="" style="width:;" class="split"> Finish</th>
  <th title="" style="width:13px;border-right:0;"> </th>
</tr>
</thead>
<tbody>
<tr class=" list-highlight">
  <td>271</td>
  <td>1</td>
  <td></td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000028E8D5&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Porter, Georgia (USA)</a>

</td>
  <td></td>
  <td>970</td>
  <td></td>
  <td>01:20:15</td>
  <td class="split">02:44:50</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000028E8D5" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>294</td>
  <td>2</td>
  <td>1</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FB6&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Oldroyd, Hannah (GBR)</a>

</td>
  <td>Saltaire Striders</td>
  <td>619</td>
  <td>18-39</td>
  <td>01:23:37</td>
  <td class="split">02:46:27</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FB6" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>297</td>
  <td>3</td>
  <td>2</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A067&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Bowman, Laura (USA)</a>

</td>
  <td>Other</td>
  <td>849</td>
  <td>18-39</td>
  <td>01:21:11</td>
  <td class="split">02:46:36</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A067" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>337</td>
  <td>4</td>
  <td>3</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000028F4FB&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Carruthers, Hayley (GBR)</a>

</td>
  <td></td>
  <td>980</td>
  <td>18-39</td>
  <td>01:25:58</td>
  <td class="split">02:47:47</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000028F4FB" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>342</td>
  <td>5</td>
  <td>4</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FA6&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Elliott, Sarah (CAN)</a>

</td>
  <td>Serpentine RC</td>
  <td>596</td>
  <td>18-39</td>
  <td>01:22:02</td>
  <td class="split">02:47:52</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FA6" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>371</td>
  <td>6</td>
  <td>5</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FCD&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Rose, Charlotte (GBR)</a>

</td>
  <td><span title="City Of Norwich AC">City Of Norwich...</span></td>
  <td>545</td>
  <td>18-39</td>
  <td>01:24:19</td>
  <td class="split">02:48:35</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FCD" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>473</td>
  <td>7</td>
  <td>6</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A005&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Vongvorachoti, Jane (GBR)</a>

</td>
  <td>Belgrave Harriers</td>
  <td>679</td>
  <td>18-39</td>
  <td>01:22:31</td>
  <td class="split">02:50:51</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A005" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>576</td>
  <td>8</td>
  <td>1</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A05B&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Grima, Claire (GBR)</a>

</td>
  <td><span title="Hercules Wimbledon AC">Hercules Wimble...</span></td>
  <td>832</td>
  <td>40-44</td>
  <td>01:21:45</td>
  <td class="split">02:53:13</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A05B" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>591</td>
  <td>9</td>
  <td>7</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000028F4AA&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">O'Regan, Johanna (GBR)</a>

</td>
  <td></td>
  <td>924</td>
  <td>18-39</td>
  <td>01:23:11</td>
  <td class="split">02:53:26</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000028F4AA" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>609</td>
  <td>10</td>
  <td>8</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FDD&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Menon, Mary (GBR)</a>

</td>
  <td><span title="Ilfracombe Running Club">Ilfracombe Runnin...</span></td>
  <td>564</td>
  <td>18-39</td>
  <td>01:23:37</td>
  <td class="split">02:53:44</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FDD" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>647</td>
  <td>11</td>
  <td>9</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FEC&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Schwiening, Georgina (GBR)</a>

</td>
  <td><span title="Cambridge &amp; Coleridge AC">Cambridge &amp; Cole...</span></td>
  <td>747</td>
  <td>18-39</td>
  <td>01:23:36</td>
  <td class="split">02:54:30</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FEC" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>712</td>
  <td>12</td>
  <td>10</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299F89&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Ward, Stacey (GBR)</a>

</td>
  <td>Herne Hill Harriers</td>
  <td>572</td>
  <td>18-39</td>
  <td>01:22:00</td>
  <td class="split">02:55:38</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299F89" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>718</td>
  <td>13</td>
  <td>11</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299F57&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Gallop, Rebecca (GBR)</a>

</td>
  <td>Newark AC</td>
  <td>507</td>
  <td>18-39</td>
  <td>01:25:17</td>
  <td class="split">02:55:43</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299F57" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>748</td>
  <td>14</td>
  <td>12</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E00002989A4&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Rabie, Mari (RSA)</a>

</td>
  <td></td>
  <td>59142</td>
  <td>18-39</td>
  <td>01:25:42</td>
  <td class="split">02:56:02</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E00002989A4" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>784</td>
  <td>15</td>
  <td>13</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299F80&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Male, Joanna (GBR)</a>

</td>
  <td>West End Runners</td>
  <td>502</td>
  <td>18-39</td>
  <td>01:25:47</td>
  <td class="split">02:56:34</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299F80" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>790</td>
  <td>16</td>
  <td>14</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A015&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Fenn, Georgie (GBR)</a>

</td>
  <td>Belgrave Harriers</td>
  <td>698</td>
  <td>18-39</td>
  <td>01:26:34</td>
  <td class="split">02:56:38</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A015" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>810</td>
  <td>17</td>
  <td>15</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299F62&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Busman, Meredith (USA)</a>

</td>
  <td>Serpentine RC</td>
  <td>522</td>
  <td>18-39</td>
  <td>01:27:11</td>
  <td class="split">02:56:55</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299F62" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>813</td>
  <td>18</td>
  <td>1</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A05E&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">heslop, maria (GBR)</a>

</td>
  <td>Tonbridge AC</td>
  <td>836</td>
  <td>50-54</td>
  <td>01:23:42</td>
  <td class="split">02:56:56</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A05E" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>892</td>
  <td>19</td>
  <td>2</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000290ED3&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Ponder, Rosamund (GBR)</a>

</td>
  <td>West 4 Harriers</td>
  <td>408</td>
  <td>40-44</td>
  <td>01:25:26</td>
  <td class="split">02:57:59</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000290ED3" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>905</td>
  <td>20</td>
  <td>16</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299F79&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Nolan, Michelle (GBR)</a>

</td>
  <td><span title="Gateshead Harriers &amp; AC">Gateshead Harri...</span></td>
  <td>492</td>
  <td>18-39</td>
  <td>01:26:38</td>
  <td class="split">02:58:07</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299F79" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>914</td>
  <td>21</td>
  <td>17</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FA2&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Bunting, Rebecca (GBR)</a>

</td>
  <td>London Heathside </td>
  <td>651</td>
  <td>18-39</td>
  <td>01:26:34</td>
  <td class="split">02:58:12</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FA2" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>977</td>
  <td>22</td>
  <td>3</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A349&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Lewis, Susan (GBR)</a>

</td>
  <td>Roundhay Runners</td>
  <td>542</td>
  <td>40-44</td>
  <td>01:27:25</td>
  <td class="split">02:58:50</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A349" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>990</td>
  <td>23</td>
  <td>18</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E00002985B0&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">HAO, Xiaofan (CHN)</a>

</td>
  <td>Other</td>
  <td>55358</td>
  <td>18-39</td>
  <td>01:28:40</td>
  <td class="split">02:58:57</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E00002985B0" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1010</td>
  <td>24</td>
  <td>19</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FE0&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Green, Tori (GBR)</a>

</td>
  <td><span title="Rugby &amp; Northampton AC">Rugby &amp; Northa...</span></td>
  <td>731</td>
  <td>18-39</td>
  <td>01:27:08</td>
  <td class="split">02:59:05</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FE0" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1055</td>
  <td>25</td>
  <td>20</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A033&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Barnes-Heeney, Dani (GBR)</a>

</td>
  <td><span title="Windsor Slough Eton &amp; Hounslow AC">Windsor Slough ...</span></td>
  <td>796</td>
  <td>18-39</td>
  <td>01:29:02</td>
  <td class="split">02:59:29</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A033" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1061</td>
  <td>26</td>
  <td>21</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FA9&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Wray, Zanthe (GBR)</a>

</td>
  <td><span title="Hallamshire Harriers Sheffield">Hallamshire Harrier...</span></td>
  <td>599</td>
  <td>18-39</td>
  <td>01:26:48</td>
  <td class="split">02:59:32</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FA9" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1064</td>
  <td>27</td>
  <td>22</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299F7E&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Owens, Katherine (GBR)</a>

</td>
  <td>Crawley AC</td>
  <td>500</td>
  <td>18-39</td>
  <td>01:29:59</td>
  <td class="split">02:59:33</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299F7E" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1083</td>
  <td>28</td>
  <td>4</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FEF&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Rea, Isobel (GBR)</a>

</td>
  <td>West 4 Harriers</td>
  <td>750</td>
  <td>40-44</td>
  <td>01:28:41</td>
  <td class="split">02:59:46</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FEF" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1088</td>
  <td>29</td>
  <td>23</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FF1&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Evans, Clara (GBR)</a>

</td>
  <td>Cardiff AAC</td>
  <td>754</td>
  <td>18-39</td>
  <td>01:24:21</td>
  <td class="split">02:59:48</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FF1" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1093</td>
  <td>30</td>
  <td>24</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FAD&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Bubb, Sophie (GBR)</a>

</td>
  <td><span title="Lymington Triathlon Club">Lymington Triathl...</span></td>
  <td>605</td>
  <td>18-39</td>
  <td>01:27:13</td>
  <td class="split">02:59:50</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FAD" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1102</td>
  <td>31</td>
  <td>1</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299F6F&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Banks, Andrea (JEY)</a>

</td>
  <td><span title="Jersey Spartan AC">Jersey Spartan...</span></td>
  <td>481</td>
  <td>45-49</td>
  <td>01:26:52</td>
  <td class="split">02:59:53</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299F6F" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1104</td>
  <td>32</td>
  <td>25</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E00002998D9&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">NEHME, PIA (LIB)</a>

</td>
  <td></td>
  <td>61551</td>
  <td>18-39</td>
  <td>01:28:24</td>
  <td class="split">02:59:54</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E00002998D9" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1106</td>
  <td>33</td>
  <td>5</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000028EF0E&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Baryga, Sarah (GBR)</a>

</td>
  <td></td>
  <td>26225</td>
  <td>40-44</td>
  <td>01:28:40</td>
  <td class="split">02:59:55</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000028EF0E" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1114</td>
  <td>34</td>
  <td>26</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FBA&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Hinton, Josie (GBR)</a>

</td>
  <td>London Heathside </td>
  <td>625</td>
  <td>18-39</td>
  <td>01:27:31</td>
  <td class="split">03:00:00</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FBA" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1123</td>
  <td>35</td>
  <td>27</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FCF&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Byrne, Annie (GBR)</a>

</td>
  <td><span title="Victoria Park Harriers and Tower Hamlets AC">Victoria Park Har...</span></td>
  <td>547</td>
  <td>18-39</td>
  <td>01:27:49</td>
  <td class="split">03:00:06</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FCF" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1125</td>
  <td>36</td>
  <td>6</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299F54&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Wright, Vicky (GBR)</a>

</td>
  <td><span title="Hyde Village Striders">Hyde Village Stri...</span></td>
  <td>474</td>
  <td>40-44</td>
  <td>01:26:55</td>
  <td class="split">03:00:07</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299F54" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1159</td>
  <td>37</td>
  <td>2</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E00002902AA&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Jackson, Debbie (GBR)</a>

</td>
  <td>Collingwood A/C</td>
  <td>936</td>
  <td>45-49</td>
  <td>01:28:58</td>
  <td class="split">03:00:33</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E00002902AA" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1161</td>
  <td>38</td>
  <td>28</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299DCA&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Knuchel, Kathrin (SUI)</a>

</td>
  <td></td>
  <td>61446</td>
  <td>18-39</td>
  <td>01:30:18</td>
  <td class="split">03:00:34</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299DCA" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1162</td>
  <td>39</td>
  <td>29</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A34B&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Sweatt, Rachel (GBR)</a>

</td>
  <td>Witham RC</td>
  <td>737</td>
  <td>18-39</td>
  <td>01:28:46</td>
  <td class="split">03:00:34</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A34B" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1166</td>
  <td>40</td>
  <td>7</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A010&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Hallside, Katy (GBR)</a>

</td>
  <td>Other</td>
  <td>691</td>
  <td>40-44</td>
  <td>01:29:05</td>
  <td class="split">03:00:37</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A010" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1193</td>
  <td>41</td>
  <td>30</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A037&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Buchanan, Catriona (GBR)</a>

</td>
  <td>Other</td>
  <td>800</td>
  <td>18-39</td>
  <td>01:29:40</td>
  <td class="split">03:01:00</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A037" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1200</td>
  <td>42</td>
  <td>2</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FF5&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Turner, Elspeth (GBR)</a>

</td>
  <td><span title="Horsham Blue Star Harriers">Horsham Blue Sta...</span></td>
  <td>657</td>
  <td>50-54</td>
  <td>01:26:36</td>
  <td class="split">03:01:02</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FF5" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1210</td>
  <td>43</td>
  <td>31</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FBF&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Mitchell, Naomi (GBR)</a>

</td>
  <td>Reading AC</td>
  <td>632</td>
  <td>18-39</td>
  <td>01:23:36</td>
  <td class="split">03:01:09</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FBF" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1219</td>
  <td>44</td>
  <td>32</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000290234&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">McCandless, Joanne (GBR)</a>

</td>
  <td></td>
  <td>33244</td>
  <td>18-39</td>
  <td>01:28:07</td>
  <td class="split">03:01:15</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000290234" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1223</td>
  <td>45</td>
  <td>33</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000028EC44&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Thompson, Liberty (GBR)</a>

</td>
  <td></td>
  <td>958</td>
  <td>18-39</td>
  <td>01:27:23</td>
  <td class="split">03:01:19</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000028EC44" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1275</td>
  <td>46</td>
  <td>34</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A0A4&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Thomas, Rachel (GBR)</a>

</td>
  <td><span title="Victoria Park Harriers and Tower Hamlets AC">Victoria Park Har...</span></td>
  <td>887</td>
  <td>18-39</td>
  <td>01:28:52</td>
  <td class="split">03:02:13</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A0A4" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1286</td>
  <td>47</td>
  <td>35</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FED&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Winstone, Sarah (GBR)</a>

</td>
  <td><span title="Lordshill Road Runners">Lordshill Road R...</span></td>
  <td>748</td>
  <td>18-39</td>
  <td>01:27:12</td>
  <td class="split">03:02:20</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FED" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1287</td>
  <td>48</td>
  <td>8</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A058&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Matthews, Katherine (GBR)</a>

</td>
  <td>Chepstow Harriers</td>
  <td>826</td>
  <td>40-44</td>
  <td>01:28:37</td>
  <td class="split">03:02:21</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A058" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1288</td>
  <td>49</td>
  <td>9</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FDE&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Wightman, Sarah (GBR)</a>

</td>
  <td><span title="Cambridge &amp; Coleridge AC">Cambridge &amp; Cole...</span></td>
  <td>729</td>
  <td>40-44</td>
  <td>01:28:57</td>
  <td class="split">03:02:24</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FDE" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1291</td>
  <td>50</td>
  <td>3</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000290EF0&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Cumber, Sarah Louise (GBR)</a>

</td>
  <td><span title="Halifax Harriers &amp; AC">Halifax Harriers...</span></td>
  <td>440</td>
  <td>45-49</td>
  <td>01:26:33</td>
  <td class="split">03:02:27</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000290EF0" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1294</td>
  <td>51</td>
  <td>36</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A0A5&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Towerton, Kate (GBR)</a>

</td>
  <td><span title="Winchester &amp; District AC">Winchester &amp; Dist...</span></td>
  <td>888</td>
  <td>18-39</td>
  <td>01:26:47</td>
  <td class="split">03:02:28</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A0A5" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1330</td>
  <td>52</td>
  <td>37</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A0AB&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Williams, Amie (GBR)</a>

</td>
  <td>Tipton Harriers</td>
  <td>896</td>
  <td>18-39</td>
  <td>01:27:54</td>
  <td class="split">03:02:56</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A0AB" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1341</td>
  <td>53</td>
  <td>38</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000028E9EA&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Bohane, Betty (GBR)</a>

</td>
  <td></td>
  <td>930</td>
  <td>18-39</td>
  <td>01:27:28</td>
  <td class="split">03:03:08</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000028E9EA" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1348</td>
  <td>54</td>
  <td>10</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000291DDF&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Xavier, Naiara-Faria (BRA)</a>

</td>
  <td></td>
  <td>59520</td>
  <td>40-44</td>
  <td>01:29:34</td>
  <td class="split">03:03:16</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000291DDF" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1368</td>
  <td>55</td>
  <td>39</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A063&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Sneddon, Alexandra (GBR)</a>

</td>
  <td><span title="Jarrow &amp; Hebburn AC">Jarrow &amp; Hebbu...</span></td>
  <td>844</td>
  <td>18-39</td>
  <td>01:25:44</td>
  <td class="split">03:03:36</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A063" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1374</td>
  <td>56</td>
  <td>40</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FCA&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Neale, Charlotte (GBR)</a>

</td>
  <td><span title="North Norfolk Beach Runners">North Norfolk B...</span></td>
  <td>540</td>
  <td>18-39</td>
  <td>01:29:00</td>
  <td class="split">03:03:41</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FCA" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1400</td>
  <td>57</td>
  <td>41</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FD9&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Winter, Rebecca (GBR)</a>

</td>
  <td><span title="Ackworth Road Runners">Ackworth Road ...</span></td>
  <td>559</td>
  <td>18-39</td>
  <td>01:29:29</td>
  <td class="split">03:04:04</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FD9" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1414</td>
  <td>58</td>
  <td>42</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FAB&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Rees, Clare (GBR)</a>

</td>
  <td><span title="Aldershot Farnham &amp; District">Aldershot Farnham...</span></td>
  <td>603</td>
  <td>18-39</td>
  <td>01:27:57</td>
  <td class="split">03:04:11</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FAB" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1418</td>
  <td>59</td>
  <td>43</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000298D98&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Rios&nbsp;&nbsp;&nbsp;&nbsp;, Maria (ARG)</a>

</td>
  <td>Other</td>
  <td>55252</td>
  <td>18-39</td>
  <td>01:29:04</td>
  <td class="split">03:04:14</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000298D98" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1427</td>
  <td>60</td>
  <td>44</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299F53&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Harvey, Rose (GBR)</a>

</td>
  <td>Clapham Chasers</td>
  <td>473</td>
  <td>18-39</td>
  <td>01:27:28</td>
  <td class="split">03:04:24</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299F53" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1442</td>
  <td>61</td>
  <td>45</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000028F422&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Davies, Rachel (GBR)</a>

</td>
  <td>Swansea Harriers</td>
  <td>951</td>
  <td>18-39</td>
  <td>01:29:19</td>
  <td class="split">03:04:36</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000028F422" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1465</td>
  <td>62</td>
  <td>1</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E00002998FA&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Schon, Karin (SWE)</a>

</td>
  <td></td>
  <td>60388</td>
  <td>55-59</td>
  <td>01:29:22</td>
  <td class="split">03:04:51</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E00002998FA" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1467</td>
  <td>63</td>
  <td>46</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A030&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Evans, SIAN (GBR)</a>

</td>
  <td><span title="Steel City Striders RC">Steel City Strid...</span></td>
  <td>793</td>
  <td>18-39</td>
  <td>01:28:45</td>
  <td class="split">03:04:53</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A030" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1468</td>
  <td>64</td>
  <td>47</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299F9C&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Custance, Lucie (GBR)</a>

</td>
  <td>Clapham Chasers</td>
  <td>642</td>
  <td>18-39</td>
  <td>01:26:52</td>
  <td class="split">03:04:54</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299F9C" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1481</td>
  <td>65</td>
  <td>48</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000028E8D6&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Trana, Gabriela (GBR)</a>

</td>
  <td></td>
  <td>982</td>
  <td>18-39</td>
  <td>01:25:59</td>
  <td class="split">03:05:04</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000028E8D6" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1495</td>
  <td>66</td>
  <td>49</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000028EEF7&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Tyler, Catrin (GBR)</a>

</td>
  <td>London Heathside</td>
  <td>941</td>
  <td>18-39</td>
  <td>01:29:55</td>
  <td class="split">03:05:17</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000028EEF7" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1497</td>
  <td>67</td>
  <td>50</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A028&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Paull, Emma (GBR)</a>

</td>
  <td>Hayle Runners</td>
  <td>724</td>
  <td>18-39</td>
  <td>01:26:48</td>
  <td class="split">03:05:18</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A028" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1533</td>
  <td>68</td>
  <td>51</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000290EFC&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Rooney, Lisa (GBR)</a>

</td>
  <td>Collingwood AC</td>
  <td>453</td>
  <td>18-39</td>
  <td>01:29:41</td>
  <td class="split">03:05:47</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000290EFC" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1537</td>
  <td>69</td>
  <td>11</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A0B1&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Prideaux, Emma (GBR)</a>

</td>
  <td>Billericay Striders</td>
  <td>906</td>
  <td>40-44</td>
  <td>01:29:49</td>
  <td class="split">03:05:51</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A0B1" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1551</td>
  <td>70</td>
  <td>4</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A074&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Godwin, Dawn (GBR)</a>

</td>
  <td><span title="Windle Valley Runners">Windle Valley Run...</span></td>
  <td>768</td>
  <td>45-49</td>
  <td>01:29:44</td>
  <td class="split">03:06:00</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A074" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1587</td>
  <td>71</td>
  <td>52</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000028F4C8&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Wood, Katherine (GBR)</a>

</td>
  <td><span title="Sale Harriers Manchester">Sale Harriers Ma...</span></td>
  <td>27542</td>
  <td>18-39</td>
  <td>01:25:41</td>
  <td class="split">03:06:23</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000028F4C8" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1591</td>
  <td>72</td>
  <td>53</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299F7B&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Mclennan, Zoe (GBR)</a>

</td>
  <td><span title="Chester Triathlon Club">Chester Triathlon...</span></td>
  <td>495</td>
  <td>18-39</td>
  <td>01:28:39</td>
  <td class="split">03:06:25</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299F7B" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1595</td>
  <td>73</td>
  <td>54</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A07E&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Parry-Williams, Jess (GBR)</a>

</td>
  <td>Les Croupiers</td>
  <td>782</td>
  <td>18-39</td>
  <td>01:30:46</td>
  <td class="split">03:06:28</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A07E" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1599</td>
  <td>74</td>
  <td>55</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FC2&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Randles, Sarah (GBR)</a>

</td>
  <td><span title="Thames Hare &amp; Hounds">Thames Hare &amp; ...</span></td>
  <td>635</td>
  <td>18-39</td>
  <td>01:28:41</td>
  <td class="split">03:06:29</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FC2" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1602</td>
  <td>75</td>
  <td>56</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FB0&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Teece, natalie (GBR)</a>

</td>
  <td>Stilton Striders</td>
  <td>609</td>
  <td>18-39</td>
  <td>01:28:55</td>
  <td class="split">03:06:30</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FB0" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1610</td>
  <td>76</td>
  <td>5</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A01A&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">hill, Sarah (GBR)</a>

</td>
  <td>Farnham Runners</td>
  <td>704</td>
  <td>45-49</td>
  <td>01:29:37</td>
  <td class="split">03:06:37</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A01A" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1626</td>
  <td>77</td>
  <td>57</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A035&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Gibson, Melissah (GBR)</a>

</td>
  <td><span title="Ealing Eagles Running Club">Ealing Eagles Run...</span></td>
  <td>798</td>
  <td>18-39</td>
  <td>01:29:00</td>
  <td class="split">03:06:49</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A035" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1633</td>
  <td>78</td>
  <td>12</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A019&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Alcaraz, Toni (GBR)</a>

</td>
  <td>March AC</td>
  <td>703</td>
  <td>40-44</td>
  <td>01:32:40</td>
  <td class="split">03:06:54</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A019" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1634</td>
  <td>79</td>
  <td>58</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A009&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Clegg, Lindsey (GBR)</a>

</td>
  <td>Horsforth Harriers</td>
  <td>683</td>
  <td>18-39</td>
  <td>01:28:30</td>
  <td class="split">03:06:55</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A009" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1641</td>
  <td>80</td>
  <td>3</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000290EF3&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Callanan, Collette (GBR)</a>

</td>
  <td>Sandhurst Joggers</td>
  <td>443</td>
  <td>50-54</td>
  <td>01:30:45</td>
  <td class="split">03:07:00</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000290EF3" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1682</td>
  <td>81</td>
  <td>59</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000028EE7F&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Stretton, Jackie (GBR)</a>

</td>
  <td><span title="Springfield Striders RC">Springfield Strid...</span></td>
  <td>933</td>
  <td>18-39</td>
  <td>01:25:15</td>
  <td class="split">03:07:31</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000028EE7F" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1689</td>
  <td>82</td>
  <td>60</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A041&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">wood, rachel (GBR)</a>

</td>
  <td><span title="Blackburn Harriers &amp; AC">Blackburn Harri...</span></td>
  <td>811</td>
  <td>18-39</td>
  <td>01:29:10</td>
  <td class="split">03:07:37</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A041" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1699</td>
  <td>83</td>
  <td>61</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000290EE0&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Brockbank, Nikki (GBR)</a>

</td>
  <td><span title="Springfield Striders RC">Springfield Strid...</span></td>
  <td>423</td>
  <td>18-39</td>
  <td>01:30:11</td>
  <td class="split">03:07:44</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000290EE0" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1714</td>
  <td>84</td>
  <td>13</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FF9&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Knowles, Jill (GBR)</a>

</td>
  <td>Other</td>
  <td>663</td>
  <td>40-44</td>
  <td>01:28:13</td>
  <td class="split">03:07:54</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FF9" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1730</td>
  <td>85</td>
  <td>62</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000028F0CA&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Collin, Clair (GBR)</a>

</td>
  <td><span title="South London Harriers">South London Ha...</span></td>
  <td>26961</td>
  <td>18-39</td>
  <td>01:32:05</td>
  <td class="split">03:08:05</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000028F0CA" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1741</td>
  <td>86</td>
  <td>63</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000028ED19&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Hazelton, Michelle (GBR)</a>

</td>
  <td></td>
  <td>25623</td>
  <td>18-39</td>
  <td>01:30:30</td>
  <td class="split">03:08:15</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000028ED19" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1753</td>
  <td>87</td>
  <td>14</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FAC&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Sarkies, Amy (GBR)</a>

</td>
  <td><span title="Rugby &amp; Northampton AC">Rugby &amp; Northa...</span></td>
  <td>604</td>
  <td>40-44</td>
  <td>01:32:12</td>
  <td class="split">03:08:20</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FAC" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1759</td>
  <td>88</td>
  <td>64</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299F6E&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Baker, Rachel (GBR)</a>

</td>
  <td>Clapham Chasers</td>
  <td>479</td>
  <td>18-39</td>
  <td>01:28:56</td>
  <td class="split">03:08:21</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299F6E" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1760</td>
  <td>89</td>
  <td>6</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299F97&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Nelson, Joanne (GBR)</a>

</td>
  <td><span title="Blackburn Harriers &amp; AC">Blackburn Harri...</span></td>
  <td>590</td>
  <td>45-49</td>
  <td>01:30:55</td>
  <td class="split">03:08:22</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299F97" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1766</td>
  <td>90</td>
  <td>15</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A34A&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Qi, Wanwen (GBR)</a>

</td>
  <td>Corby AC</td>
  <td>560</td>
  <td>40-44</td>
  <td>01:29:33</td>
  <td class="split">03:08:26</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A34A" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1769</td>
  <td>91</td>
  <td>65</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FD5&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Logan, Sheena (GBR)</a>

</td>
  <td>Other</td>
  <td>555</td>
  <td>18-39</td>
  <td>01:28:29</td>
  <td class="split">03:08:28</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FD5" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1810</td>
  <td>92</td>
  <td>66</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000298CB4&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Snider-Rodriguez, Jessica (USA)</a>

</td>
  <td></td>
  <td>57723</td>
  <td>18-39</td>
  <td>01:31:41</td>
  <td class="split">03:08:54</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000298CB4" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1814</td>
  <td>93</td>
  <td>16</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299FFC&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Ford, Sally (GBR)</a>

</td>
  <td>100 Marathon Club</td>
  <td>667</td>
  <td>40-44</td>
  <td>01:32:00</td>
  <td class="split">03:08:57</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299FFC" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1816</td>
  <td>94</td>
  <td>67</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000029A029&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Faram, Jane (GBR)</a>

</td>
  <td><span title="Southville Running Club">Southville Runnin...</span></td>
  <td>726</td>
  <td>18-39</td>
  <td>01:29:02</td>
  <td class="split">03:08:57</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000029A029" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1828</td>
  <td>95</td>
  <td>68</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000298E8C&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Walters, Allie (USA)</a>

</td>
  <td>Other</td>
  <td>56115</td>
  <td>18-39</td>
  <td>01:35:07</td>
  <td class="split">03:09:03</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000298E8C" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1839</td>
  <td>96</td>
  <td>69</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000290EEF&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Ede, Tamsin (GBR)</a>

</td>
  <td>Clapham Chasers</td>
  <td>439</td>
  <td>18-39</td>
  <td>01:30:33</td>
  <td class="split">03:09:09</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000290EEF" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1844</td>
  <td>97</td>
  <td>70</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000028F2A1&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Lines, Samantha (GBR)</a>

</td>
  <td>Waveney Valley AC</td>
  <td>27604</td>
  <td>18-39</td>
  <td>01:33:03</td>
  <td class="split">03:09:12</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000028F2A1" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1863</td>
  <td>98</td>
  <td>17</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E000028FBF3&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">BAXTER, MARIE (GBR)</a>

</td>
  <td><span title="Garioch Road Runners">Garioch Road Ru...</span></td>
  <td>31215</td>
  <td>40-44</td>
  <td>01:27:54</td>
  <td class="split">03:09:25</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E000028FBF3" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr class=" list-highlight">
  <td>1867</td>
  <td>99</td>
  <td>4</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299F71&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Riddell-Webster, C. Alice (GBR)</a>

</td>
  <td><span title="Fulham Running Club">Fulham Running C...</span></td>
  <td>483</td>
  <td>50-54</td>
  <td>01:30:15</td>
  <td class="split">03:09:27</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299F71" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
<tr>
  <td>1885</td>
  <td>100</td>
  <td>71</td>
  <td>» <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9999990F5ECC8E0000299F74&amp;lang=EN_CAP&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;search_event=MAS">Charlton, Catherine (GBR)</a>

</td>
  <td>Notts AC</td>
  <td>486</td>
  <td>18-39</td>
  <td>01:32:33</td>
  <td class="split">03:09:37</td>
  <td style="border-right:0;"><a href="?num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W&amp;event=MAS&amp;favorite_add=9999990F5ECC8E0000299F74" class="icon s"><img src="//assets.mikatiming.com/img/mt/results/default/icons/add.svg" alt="Add Runner To 'My Favourites'" title="Add Runner To 'My Favourites'"></a></td>
</tr>
</tbody>
</table>
<script type="text/javascript">
                jQuery().ready(function () {
                    jQuery("table.list-table thead td[title]").tooltip({position: { my: "left top-45", at: "left top" }});
                });
            </script>
<div class="back">
<a class="" href="?pid=start&amp;event=MAS&amp;num_results=100&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W">Back / New Search</a>
</div>
<div class="back reload">
<a class="" href="?event=MAS&amp;num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W">Reload</a>
</div>
<div class="back print">
<a class="" href="#" onclick="open_print('?print=1&amp;event=MAS&amp;num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W');">Print</a>
</div>
<div class="pages"><span class="pages-label">Page: </span>
<a href="?page=1&amp;event=MAS&amp;num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W" id="selected">1</a><a href="?page=2&amp;event=MAS&amp;num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W">2</a><a href="?page=3&amp;event=MAS&amp;num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W">3</a><span>...</span><a href="?page=165&amp;event=MAS&amp;num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W">165</a><a class="pages-nav-button" href="?page=2&amp;event=MAS&amp;num_results=100&amp;pid=list&amp;search%5Bage_class%5D=%25&amp;search%5Bsex%5D=W">&gt;</a>
</div>
</div><div style="clear:both"></div>
</div><!-- end cbox-content -->

<!-- cbox include end -->
</div>


</div><!-- results end -->
</div><!-- content end -->
</div><!-- main-content end -->
<!-- main end -->

<!-- footer start -->
</div><!-- end main --><div class="popup-info" style="display:none;" id="popup-info"></div>
<div class="popup" style="display:none;" id="popup"></div>
<div id="cconsent-overlay" style="display:none;"></div>
<div class="bottom-box bg pid-list" id="bottom-box-bg">

</div>





<input class="hidden" id="identified_1" autocomplete="off" name="16eb4399-1f99-89d1-01e5-90a4bd4a0f15" data-last-search-value=""><ul class="dropdown-menu quicksearch-results" style="z-index: 2001;"></ul></body></html>"""

In [4]:
soup = BeautifulSoup(raw_html, 'html.parser')

In [5]:
name_nodes = soup.select('.list-field.type-fullname')

In [6]:
# name_nodes = soup.select('.list-field.type-eval')

In [7]:
name_nodes = name_nodes[1:]

In [8]:
len(name_nodes)

0

In [9]:
name_nodes[0].get_text(strip=True)

'Ghebresilasie, Weynay (ERI)'

In [10]:
def get_name(name_node):
  text = name_node.get_text()
  name = text[:text.find("(")].strip()
  return name

def get_country(name_node):
  country_text = name_node.get_text()
  country_item = country_text[country_text.find("(") + 1 : country_text.find(")")]
  return country_item

In [11]:
list_all_names = []
list_countries = []
for name_node in name_nodes:
  list_all_names.append(get_name(name_node))
  list_countries.append(get_country(name_node))

In [12]:
list_countries[:5]

['ERI', 'GBR', 'GBR', 'GBR', 'GBR']

In [13]:
len(list_countries)

100

In [14]:
len(list_all_names)

100

In [15]:
overall_nodes = soup.select('.list-field.type-place.place-secondary.hidden-xs.numeric')

In [16]:
overall_nodes[:5]

[<div class="list-field type-place place-secondary hidden-xs numeric" style="width: 60px">1</div>,
 <div class="list-field type-place place-secondary hidden-xs numeric" style="width: 60px">1</div>,
 <div class="list-field type-place place-secondary hidden-xs numeric" style="width: 60px">2</div>,
 <div class="list-field type-place place-secondary hidden-xs numeric" style="width: 60px">2</div>,
 <div class="list-field type-place place-secondary hidden-xs numeric" style="width: 60px">3</div>]

In [17]:
def get_overall(overall_node):
    # Convert the string to a BeautifulSoup object if it isn't already
    if isinstance(overall_node, str):
        overall_node = BeautifulSoup(overall_node, 'html.parser')
    return overall_node.get_text(strip=True)

In [18]:
# def get_overall(overall_node):
#   return overall_node.get_text()

In [19]:
bib_nodes = soup.select('.list-field.type-field')

In [20]:
bib_nodes[:10]

[<div class="list-field type-field hidden-xs" style="width: 150px"><div class="visible-xs-block visible-sm-block list-label">Club</div>Club</div>,
 <div class="list-field type-field" style="width: 90px"><div class="visible-xs-block visible-sm-block list-label">Runner Number</div>Runner Number</div>,
 <div class="list-field type-field hidden-xs" style="width: 150px"><div class="visible-xs-block visible-sm-block list-label">Club</div><span class="text-muted">–</span></div>,
 <div class="list-field type-field" style="width: 90px"><div class="visible-xs-block visible-sm-block list-label">Runner Number</div>1451</div>,
 <div class="list-field type-field hidden-xs" style="width: 150px"><div class="visible-xs-block visible-sm-block list-label">Club</div><span class="text-muted">–</span></div>,
 <div class="list-field type-field" style="width: 90px"><div class="visible-xs-block visible-sm-block list-label">Runner Number</div>1291</div>,
 <div class="list-field type-field hidden-xs" style="width: 150px"><div class="visible-xs-block visible-sm-block list-label">Club</div><span class="text-muted">–</span></div>,
 <div class="list-field type-field" style="width: 90px"><div class="visible-xs-block visible-sm-block list-label">Runner Number</div>1246</div>,
 <div class="list-field type-field hidden-xs" style="width: 150px"><div class="visible-xs-block visible-sm-block list-label">Club</div><span class="text-muted">–</span></div>,
 <div class="list-field type-field" style="width: 90px"><div class="visible-xs-block visible-sm-block list-label">Runner Number</div>1456</div>]

In [21]:
def get_bib(bib_node):
    runner_number_label = bib_node.find('div', text='Runner Number')
    if runner_number_label:
        parent_div_text = runner_number_label.parent.get_text(strip=True)
        return parent_div_text.split('Runner Number')[-1].strip()

In [22]:
# def get_bib(bib_node):
#     runner_number_label = bib_node.find('div', text='Running Number')
#     if runner_number_label:
#         parent_div_text = runner_number_label.parent.get_text(strip=True)
#         return parent_div_text.split('Running Number')[-1].strip()

In [23]:
# def get_bib(bib_node):
#   return bib_node.get_text()

In [24]:
time_nodes = soup.select('.list-field.type-time:contains("Finish")')

/usr/local/lib/python3.10/dist-packages/soupsieve/css_parser.py:856: FutureWarning: The pseudo class ':contains' is deprecated, ':-soup-contains' should be used moving forward.
  warnings.warn(  # noqa: B028

In [25]:
time_nodes = time_nodes[1:]

In [26]:
time_node = time_nodes[0].get_text()

In [27]:
time_node.split('Finish')[-1].strip()

'02:17:21'

In [28]:
def get_time(time_node):
  return time_node.get_text().split('Finish')[-1].strip()

In [29]:
division_nodes = soup.select('.list-field.type-age_class')

In [30]:
len(division_nodes)

101

In [31]:
def get_division(division_node):
  return division_node.get_text()

In [32]:
list_overall = [get_overall(node) for i, node in enumerate(overall_nodes) if i % 2 == 0]

list_bib = []
for bib_node in bib_nodes:
  list_bib.append(get_bib(bib_node))

list_times = []
for time_node in time_nodes:
  list_times.append(get_time(time_node))

list_divisions = []
for division_node in division_nodes:
  list_divisions.append(get_division(division_node))

<ipython-input-21-689cd7ad8988>:2: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  runner_number_label = bib_node.find('div', text='Runner Number')

In [33]:
list_overall[:30]

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30']

In [34]:
len(list_overall)

100

In [35]:
len(list_times)

100

In [36]:
list_bib = [bib for bib in list_bib if bib is not None]
len(list_bib)

101

In [37]:
list_bib = list_bib[1:]

In [38]:
len(list_bib)

100

In [39]:
list_divisions = list_divisions[1:]
len(list_divisions)

100

In [40]:
data = {
    'Name': list_all_names,
    'Division': list_divisions,
    'Country': list_countries,
    'BIB': list_bib,
    'Overall Place': list_overall,
    'Time': list_times
}

In [41]:
df = pd.DataFrame(data)

In [42]:
df

,Name,Division,Country,BIB,Overall Place,Time
0,"Ghebresilasie, Weynay",Category18-39,ERI,1451,1,02:17:21
1,"Gilbert, John",Category18-39,GBR,1291,2,02:19:03
2,"Johnson, Ben",Category18-39,GBR,1246,3,02:20:03
3,"Milne, Alex",Category18-39,GBR,1456,4,02:20:08
4,"Ruddy, Craig",Category18-39,GBR,1362,5,02:20:29
...,...,...,...,...,...,...
95,"Schroy, Brian",Category18-39,USA,56764,96,02:30:25
96,"Steel, Daniel",Category18-39,GBR,1406,97,02:30:31
97,"Tighe, Josh",Category18-39,GBR,1691,98,02:30:32
98,"Harrington, Scott",Category40-44,GBR,1292,99,02:30:41
99,"Barnett, Jamie",Category18-39,GBR,1408,100,02:30:41

In [43]:
missing_values = df.isnull().sum()
missing_values

Name             0
Division         0
Country          0
BIB              0
Overall Place    0
Time             0
dtype: int64

In [44]:
df['Gender'] = gender
df

,Name,Division,Country,BIB,Overall Place,Time,Gender
0,"Ghebresilasie, Weynay",Category18-39,ERI,1451,1,02:17:21,M
1,"Gilbert, John",Category18-39,GBR,1291,2,02:19:03,M
2,"Johnson, Ben",Category18-39,GBR,1246,3,02:20:03,M
3,"Milne, Alex",Category18-39,GBR,1456,4,02:20:08,M
4,"Ruddy, Craig",Category18-39,GBR,1362,5,02:20:29,M
...,...,...,...,...,...,...,...
95,"Schroy, Brian",Category18-39,USA,56764,96,02:30:25,M
96,"Steel, Daniel",Category18-39,GBR,1406,97,02:30:31,M
97,"Tighe, Josh",Category18-39,GBR,1691,98,02:30:32,M
98,"Harrington, Scott",Category40-44,GBR,1292,99,02:30:41,M
99,"Barnett, Jamie",Category18-39,GBR,1408,100,02:30:41,M

In [45]:
df['Last Name'] = df['Name'].str.split(',').str[0]
df['First Name'] = df['Name'].str.split(',').str[1].str.strip()

df.drop('Name', axis=1, inplace=True)
df

,Division,Country,BIB,Overall Place,Time,Gender,Last Name,First Name
0,Category18-39,ERI,1451,1,02:17:21,M,Ghebresilasie,Weynay
1,Category18-39,GBR,1291,2,02:19:03,M,Gilbert,John
2,Category18-39,GBR,1246,3,02:20:03,M,Johnson,Ben
3,Category18-39,GBR,1456,4,02:20:08,M,Milne,Alex
4,Category18-39,GBR,1362,5,02:20:29,M,Ruddy,Craig
...,...,...,...,...,...,...,...,...
95,Category18-39,USA,56764,96,02:30:25,M,Schroy,Brian
96,Category18-39,GBR,1406,97,02:30:31,M,Steel,Daniel
97,Category18-39,GBR,1691,98,02:30:32,M,Tighe,Josh
98,Category40-44,GBR,1292,99,02:30:41,M,Harrington,Scott
99,Category18-39,GBR,1408,100,02:30:41,M,Barnett,Jamie

In [46]:
df['Year'] = year
df

,Division,Country,BIB,Overall Place,Time,Gender,Last Name,First Name,Year
0,Category18-39,ERI,1451,1,02:17:21,M,Ghebresilasie,Weynay,2019
1,Category18-39,GBR,1291,2,02:19:03,M,Gilbert,John,2019
2,Category18-39,GBR,1246,3,02:20:03,M,Johnson,Ben,2019
3,Category18-39,GBR,1456,4,02:20:08,M,Milne,Alex,2019
4,Category18-39,GBR,1362,5,02:20:29,M,Ruddy,Craig,2019
...,...,...,...,...,...,...,...,...,...
95,Category18-39,USA,56764,96,02:30:25,M,Schroy,Brian,2019
96,Category18-39,GBR,1406,97,02:30:31,M,Steel,Daniel,2019
97,Category18-39,GBR,1691,98,02:30:32,M,Tighe,Josh,2019
98,Category40-44,GBR,1292,99,02:30:41,M,Harrington,Scott,2019
99,Category18-39,GBR,1408,100,02:30:41,M,Barnett,Jamie,2019

In [47]:
df['Division'] = df['Division'].str.replace('Category', '')
df

,Division,Country,BIB,Overall Place,Time,Gender,Last Name,First Name,Year
0,18-39,ERI,1451,1,02:17:21,M,Ghebresilasie,Weynay,2019
1,18-39,GBR,1291,2,02:19:03,M,Gilbert,John,2019
2,18-39,GBR,1246,3,02:20:03,M,Johnson,Ben,2019
3,18-39,GBR,1456,4,02:20:08,M,Milne,Alex,2019
4,18-39,GBR,1362,5,02:20:29,M,Ruddy,Craig,2019
...,...,...,...,...,...,...,...,...,...
95,18-39,USA,56764,96,02:30:25,M,Schroy,Brian,2019
96,18-39,GBR,1406,97,02:30:31,M,Steel,Daniel,2019
97,18-39,GBR,1691,98,02:30:32,M,Tighe,Josh,2019
98,40-44,GBR,1292,99,02:30:41,M,Harrington,Scott,2019
99,18-39,GBR,1408,100,02:30:41,M,Barnett,Jamie,2019

In [48]:
df['Seconds'] = pd.to_timedelta(df['Time']).dt.total_seconds().astype(int)
df

,Division,Country,BIB,Overall Place,Time,Gender,Last Name,First Name,Year,Seconds
0,18-39,ERI,1451,1,02:17:21,M,Ghebresilasie,Weynay,2019,8241
1,18-39,GBR,1291,2,02:19:03,M,Gilbert,John,2019,8343
2,18-39,GBR,1246,3,02:20:03,M,Johnson,Ben,2019,8403
3,18-39,GBR,1456,4,02:20:08,M,Milne,Alex,2019,8408
4,18-39,GBR,1362,5,02:20:29,M,Ruddy,Craig,2019,8429
...,...,...,...,...,...,...,...,...,...,...
95,18-39,USA,56764,96,02:30:25,M,Schroy,Brian,2019,9025
96,18-39,GBR,1406,97,02:30:31,M,Steel,Daniel,2019,9031
97,18-39,GBR,1691,98,02:30:32,M,Tighe,Josh,2019,9032
98,40-44,GBR,1292,99,02:30:41,M,Harrington,Scott,2019,9041
99,18-39,GBR,1408,100,02:30:41,M,Barnett,Jamie,2019,9041

In [49]:
new_column_order = [
    'Last Name', 'First Name', 'Division', 'Country', 'BIB', 'Overall Place',
    'Time', 'Seconds', 'Year', 'Gender'
]

df = df[new_column_order]
df

,Last Name,First Name,Division,Country,BIB,Overall Place,Time,Seconds,Year,Gender
0,Ghebresilasie,Weynay,18-39,ERI,1451,1,02:17:21,8241,2019,M
1,Gilbert,John,18-39,GBR,1291,2,02:19:03,8343,2019,M
2,Johnson,Ben,18-39,GBR,1246,3,02:20:03,8403,2019,M
3,Milne,Alex,18-39,GBR,1456,4,02:20:08,8408,2019,M
4,Ruddy,Craig,18-39,GBR,1362,5,02:20:29,8429,2019,M
...,...,...,...,...,...,...,...,...,...,...
95,Schroy,Brian,18-39,USA,56764,96,02:30:25,9025,2019,M
96,Steel,Daniel,18-39,GBR,1406,97,02:30:31,9031,2019,M
97,Tighe,Josh,18-39,GBR,1691,98,02:30:32,9032,2019,M
98,Harrington,Scott,40-44,GBR,1292,99,02:30:41,9041,2019,M
99,Barnett,Jamie,18-39,GBR,1408,100,02:30:41,9041,2019,M

In [50]:
df.to_csv(f"London_Marathon_{gender}{year}.csv")

In [55]:
df2014f = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/london_data/2014f.csv")
df2014m = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/london_data/2014m.csv")
df2015f = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/london_data/2015f.csv")
df2015m = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/london_data/2015m.csv")
df2016f = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/london_data/2016f.csv")
df2016m = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/london_data/2016m.csv")
df2017f = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/london_data/2017f.csv")
df2017m = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/london_data/2017m.csv")
df2018f = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/london_data/2018f.csv")
df2018m = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/london_data/2018m.csv")

In [56]:
dfs = [df2014f, df2014m, df2015f, df2015m, df2016f, df2016m, df2017f, df2017m, df2018f, df2018m]
for dfa in dfs:
    dfa.rename(columns={'Runner no': 'BIB'}, inplace=True)

In [57]:
for dfa in dfs:
  print(dfa.head(3))

   Place overall                    Name  BIB Category Finish time
0             69  » Duncan, Nicola (IRL)  426    18-39     2:33:28
1            191  » Briscoe, Julie (GBR)  374    18-39     2:39:43
2            197      » Bird, Sara (GBR)  521    18-39     2:39:55
   Place overall                   Name   BIB Category Finish time
0              1    » Way, Steven (GBR)   943    18-39     2:16:27
1              2  » Gilbert, John (GBR)   851    18-39     2:16:46
2              3    » Pepper, Jon (GBR)  1043    18-39     2:19:59
   Place overall                      Name    BIB Category   FINISH
0            203  » Radcliffe, Paula (GBR)  25371    40-44  2:36:55
1            220  » Connolly, Breege (GBR)    417    18-39  2:37:24
2            225      » Spink, Jenny (GBR)    379    18-39  2:37:35
   Place overall                   Name   BIB Category   FINISH
0              1   » Kimpton, Ian (GBR)  1147    18-39  2:15:51
1              2  » Gilbert, John (GBR)   910    18-39  2:18:12
2              3   » Scott, Aaron (GBR)  1252    18-39  2:20:45
   Place overall                   Name  BIB Category   FINISH
0            125  » Barlow, Tracy (GBR)  289    18-39  2:33:20
1            214     » Muir, Tina (GBR)  645    18-39  2:37:35
2            228   » Munn, Hayley (GBR)  494    18-39  2:38:04
   Place overall                       Name   BIB Category   FINISH
0              1        » Hehir, Sean (IRL)  1000    18-39  2:17:20
1              2  » Martelletti, Paul (GBR)  1288    18-39  2:17:26
2              3     » Frazer, Thomas (IRL)  1316    18-39  2:19:17
   Place overall                    Name  BIB Category   Finish
0            201  » Boniface, Anna (GBR)  666    18-39  2:37:07
1            287   » Clements, Amy (GBR)  823    18-39  2:39:11
2            298    » Davis, Julia (GBR)  715    18-39  2:39:27
   Place overall                     Name   BIB Category   Finish
0              1  » Griffiths, Josh (GBR)  1154    18-39  2:14:49
1              2      » Hehir, Sean (GBR)  1454    18-39  2:16:18
2              3      » Sharp, Matt (GBR)  1825    18-39  2:17:45
   Overall Place                     Name  BIB Division     Time
0            271  » Porter, Georgia (USA)  970    18-39  2:44:50
1            294  » Oldroyd, Hannah (GBR)  619    18-39  2:46:27
2            297    » Bowman, Laura (USA)  849    18-39  2:46:36
   Place overall                    Name   BIB Category   Finish
0              1  » Wallis, Daniel (GBR)  2007    18-39  2:19:40
1              2   » Gilbert, John (GBR)  1436    18-39  2:20:19
2              3  » O'Hanlon, Gary (IRL)  1319    40-44  2:21:14

In [58]:
for dfa in dfs:
  dfa.rename(columns={'Category':'Division'}, inplace=True)

In [59]:
for dfa in dfs:
  print(dfa.head(3))

   Place overall                    Name  BIB Division Finish time
0             69  » Duncan, Nicola (IRL)  426    18-39     2:33:28
1            191  » Briscoe, Julie (GBR)  374    18-39     2:39:43
2            197      » Bird, Sara (GBR)  521    18-39     2:39:55
   Place overall                   Name   BIB Division Finish time
0              1    » Way, Steven (GBR)   943    18-39     2:16:27
1              2  » Gilbert, John (GBR)   851    18-39     2:16:46
2              3    » Pepper, Jon (GBR)  1043    18-39     2:19:59
   Place overall                      Name    BIB Division   FINISH
0            203  » Radcliffe, Paula (GBR)  25371    40-44  2:36:55
1            220  » Connolly, Breege (GBR)    417    18-39  2:37:24
2            225      » Spink, Jenny (GBR)    379    18-39  2:37:35
   Place overall                   Name   BIB Division   FINISH
0              1   » Kimpton, Ian (GBR)  1147    18-39  2:15:51
1              2  » Gilbert, John (GBR)   910    18-39  2:18:12
2              3   » Scott, Aaron (GBR)  1252    18-39  2:20:45
   Place overall                   Name  BIB Division   FINISH
0            125  » Barlow, Tracy (GBR)  289    18-39  2:33:20
1            214     » Muir, Tina (GBR)  645    18-39  2:37:35
2            228   » Munn, Hayley (GBR)  494    18-39  2:38:04
   Place overall                       Name   BIB Division   FINISH
0              1        » Hehir, Sean (IRL)  1000    18-39  2:17:20
1              2  » Martelletti, Paul (GBR)  1288    18-39  2:17:26
2              3     » Frazer, Thomas (IRL)  1316    18-39  2:19:17
   Place overall                    Name  BIB Division   Finish
0            201  » Boniface, Anna (GBR)  666    18-39  2:37:07
1            287   » Clements, Amy (GBR)  823    18-39  2:39:11
2            298    » Davis, Julia (GBR)  715    18-39  2:39:27
   Place overall                     Name   BIB Division   Finish
0              1  » Griffiths, Josh (GBR)  1154    18-39  2:14:49
1              2      » Hehir, Sean (GBR)  1454    18-39  2:16:18
2              3      » Sharp, Matt (GBR)  1825    18-39  2:17:45
   Overall Place                     Name  BIB Division     Time
0            271  » Porter, Georgia (USA)  970    18-39  2:44:50
1            294  » Oldroyd, Hannah (GBR)  619    18-39  2:46:27
2            297    » Bowman, Laura (USA)  849    18-39  2:46:36
   Place overall                    Name   BIB Division   Finish
0              1  » Wallis, Daniel (GBR)  2007    18-39  2:19:40
1              2   » Gilbert, John (GBR)  1436    18-39  2:20:19
2              3  » O'Hanlon, Gary (IRL)  1319    40-44  2:21:14

In [60]:
def split_name_country(name):
    # Remove the "»" character
    name = name.replace('»', '').strip()

    # Split by comma to get last name and the rest
    parts = name.split(',')
    last_name = parts[0].strip() if len(parts) > 0 else ''

    # Check if there's a first name and country part
    if len(parts) > 1:
        first_name_country = parts[1].strip()

        # Extract country code by finding text in parentheses
        country = first_name_country[first_name_country.find("(")+1:first_name_country.find(")")]
        # Remove the country code and parentheses from the first name
        first_name = first_name_country.replace(f'({country})', '').strip()
    else:
        first_name, country = '', ''

    return last_name, first_name, country

# Apply the function to each DataFrame
for df in dfs:
    df[['Last Name', 'First Name', 'Country']] = df.apply(lambda row: split_name_country(row['Name']), axis=1, result_type='expand')

In [61]:
for df in dfs:
  print(df.head(3))

   Place overall                    Name  BIB Division Finish time Last Name  \
0             69  » Duncan, Nicola (IRL)  426    18-39     2:33:28    Duncan
1            191  » Briscoe, Julie (GBR)  374    18-39     2:39:43   Briscoe
2            197      » Bird, Sara (GBR)  521    18-39     2:39:55      Bird

  First Name Country
0     Nicola     IRL
1      Julie     GBR
2       Sara     GBR
   Place overall                   Name   BIB Division Finish time Last Name  \
0              1    » Way, Steven (GBR)   943    18-39     2:16:27       Way
1              2  » Gilbert, John (GBR)   851    18-39     2:16:46   Gilbert
2              3    » Pepper, Jon (GBR)  1043    18-39     2:19:59    Pepper

  First Name Country
0     Steven     GBR
1       John     GBR
2        Jon     GBR
   Place overall                      Name    BIB Division   FINISH  \
0            203  » Radcliffe, Paula (GBR)  25371    40-44  2:36:55
1            220  » Connolly, Breege (GBR)    417    18-39  2:37:24
2            225      » Spink, Jenny (GBR)    379    18-39  2:37:35

   Last Name First Name Country
0  Radcliffe      Paula     GBR
1   Connolly     Breege     GBR
2      Spink      Jenny     GBR
   Place overall                   Name   BIB Division   FINISH Last Name  \
0              1   » Kimpton, Ian (GBR)  1147    18-39  2:15:51   Kimpton
1              2  » Gilbert, John (GBR)   910    18-39  2:18:12   Gilbert
2              3   » Scott, Aaron (GBR)  1252    18-39  2:20:45     Scott

  First Name Country
0        Ian     GBR
1       John     GBR
2      Aaron     GBR
   Place overall                   Name  BIB Division   FINISH Last Name  \
0            125  » Barlow, Tracy (GBR)  289    18-39  2:33:20    Barlow
1            214     » Muir, Tina (GBR)  645    18-39  2:37:35      Muir
2            228   » Munn, Hayley (GBR)  494    18-39  2:38:04      Munn

  First Name Country
0      Tracy     GBR
1       Tina     GBR
2     Hayley     GBR
   Place overall                       Name   BIB Division   FINISH  \
0              1        » Hehir, Sean (IRL)  1000    18-39  2:17:20
1              2  » Martelletti, Paul (GBR)  1288    18-39  2:17:26
2              3     » Frazer, Thomas (IRL)  1316    18-39  2:19:17

     Last Name First Name Country
0        Hehir       Sean     IRL
1  Martelletti       Paul     GBR
2       Frazer     Thomas     IRL
   Place overall                    Name  BIB Division   Finish Last Name  \
0            201  » Boniface, Anna (GBR)  666    18-39  2:37:07  Boniface
1            287   » Clements, Amy (GBR)  823    18-39  2:39:11  Clements
2            298    » Davis, Julia (GBR)  715    18-39  2:39:27     Davis

  First Name Country
0       Anna     GBR
1        Amy     GBR
2      Julia     GBR
   Place overall                     Name   BIB Division   Finish  Last Name  \
0              1  » Griffiths, Josh (GBR)  1154    18-39  2:14:49  Griffiths
1              2      » Hehir, Sean (GBR)  1454    18-39  2:16:18      Hehir
2              3      » Sharp, Matt (GBR)  1825    18-39  2:17:45      Sharp

  First Name Country
0       Josh     GBR
1       Sean     GBR
2       Matt     GBR
   Overall Place                     Name  BIB Division     Time Last Name  \
0            271  » Porter, Georgia (USA)  970    18-39  2:44:50    Porter
1            294  » Oldroyd, Hannah (GBR)  619    18-39  2:46:27   Oldroyd
2            297    » Bowman, Laura (USA)  849    18-39  2:46:36    Bowman

  First Name Country
0    Georgia     USA
1     Hannah     GBR
2      Laura     USA
   Place overall                    Name   BIB Division   Finish Last Name  \
0              1  » Wallis, Daniel (GBR)  2007    18-39  2:19:40    Wallis
1              2   » Gilbert, John (GBR)  1436    18-39  2:20:19   Gilbert
2              3  » O'Hanlon, Gary (IRL)  1319    40-44  2:21:14  O'Hanlon

  First Name Country
0     Daniel     GBR
1       John     GBR
2       Gary     IRL

In [62]:
df2014f.head(4)

,Place overall,Name,BIB,Division,Finish time,Last Name,First Name,Country
0,69,"» Duncan, Nicola (IRL)",426,18-39,2:33:28,Duncan,Nicola,IRL
1,191,"» Briscoe, Julie (GBR)",374,18-39,2:39:43,Briscoe,Julie,GBR
2,197,"» Bird, Sara (GBR)",521,18-39,2:39:55,Bird,Sara,GBR
3,208,"» Munn, Hayley (GBR)",273,18-39,2:40:35,Munn,Hayley,GBR

In [63]:
for df in dfs:
  df.drop('Name', axis=1, inplace=True)

In [64]:
year = 2014

for i in range(0, len(dfs), 2):
    female_df = dfs[i]
    male_df = dfs[i+1]
    female_df['Year'] = year
    male_df['Year'] = year
    year += 1

dfs[0].head()

   Place overall  BIB Division Finish time Last Name First Name Country  Year
0             69  426    18-39     2:33:28    Duncan     Nicola     IRL  2014
1            191  374    18-39     2:39:43   Briscoe      Julie     GBR  2014
2            197  521    18-39     2:39:55      Bird       Sara     GBR  2014
3            208  273    18-39     2:40:35      Munn     Hayley     GBR  2014
4            370  410    18-39     2:44:59  Fletcher      Shona     GBR  2014

In [65]:
for dfa in dfs:
  dfa.rename(columns={'Place overall':'Overall Place'}, inplace=True)

In [66]:
for df in dfs:
  print(df.head(3))

   Overall Place  BIB Division Finish time Last Name First Name Country  Year
0             69  426    18-39     2:33:28    Duncan     Nicola     IRL  2014
1            191  374    18-39     2:39:43   Briscoe      Julie     GBR  2014
2            197  521    18-39     2:39:55      Bird       Sara     GBR  2014
   Overall Place   BIB Division Finish time Last Name First Name Country  Year
0              1   943    18-39     2:16:27       Way     Steven     GBR  2014
1              2   851    18-39     2:16:46   Gilbert       John     GBR  2014
2              3  1043    18-39     2:19:59    Pepper        Jon     GBR  2014
   Overall Place    BIB Division   FINISH  Last Name First Name Country  Year
0            203  25371    40-44  2:36:55  Radcliffe      Paula     GBR  2015
1            220    417    18-39  2:37:24   Connolly     Breege     GBR  2015
2            225    379    18-39  2:37:35      Spink      Jenny     GBR  2015
   Overall Place   BIB Division   FINISH Last Name First Name Country  Year
0              1  1147    18-39  2:15:51   Kimpton        Ian     GBR  2015
1              2   910    18-39  2:18:12   Gilbert       John     GBR  2015
2              3  1252    18-39  2:20:45     Scott      Aaron     GBR  2015
   Overall Place  BIB Division   FINISH Last Name First Name Country  Year
0            125  289    18-39  2:33:20    Barlow      Tracy     GBR  2016
1            214  645    18-39  2:37:35      Muir       Tina     GBR  2016
2            228  494    18-39  2:38:04      Munn     Hayley     GBR  2016
   Overall Place   BIB Division   FINISH    Last Name First Name Country  Year
0              1  1000    18-39  2:17:20        Hehir       Sean     IRL  2016
1              2  1288    18-39  2:17:26  Martelletti       Paul     GBR  2016
2              3  1316    18-39  2:19:17       Frazer     Thomas     IRL  2016
   Overall Place  BIB Division   Finish Last Name First Name Country  Year
0            201  666    18-39  2:37:07  Boniface       Anna     GBR  2017
1            287  823    18-39  2:39:11  Clements        Amy     GBR  2017
2            298  715    18-39  2:39:27     Davis      Julia     GBR  2017
   Overall Place   BIB Division   Finish  Last Name First Name Country  Year
0              1  1154    18-39  2:14:49  Griffiths       Josh     GBR  2017
1              2  1454    18-39  2:16:18      Hehir       Sean     GBR  2017
2              3  1825    18-39  2:17:45      Sharp       Matt     GBR  2017
   Overall Place  BIB Division     Time Last Name First Name Country  Year
0            271  970    18-39  2:44:50    Porter    Georgia     USA  2018
1            294  619    18-39  2:46:27   Oldroyd     Hannah     GBR  2018
2            297  849    18-39  2:46:36    Bowman      Laura     USA  2018
   Overall Place   BIB Division   Finish Last Name First Name Country  Year
0              1  2007    18-39  2:19:40    Wallis     Daniel     GBR  2018
1              2  1436    18-39  2:20:19   Gilbert       John     GBR  2018
2              3  1319    40-44  2:21:14  O'Hanlon       Gary     IRL  2018

In [67]:
df2014f['Gender'] = 'F'
df2014m['Gender'] = 'M'
df2015f['Gender'] = 'F'
df2015m['Gender'] = 'M'
df2016f['Gender'] = 'F'
df2016m['Gender'] = 'M'
df2017f['Gender'] = 'F'
df2017m['Gender'] = 'M'
df2018f['Gender'] = 'F'
df2018m['Gender'] = 'M'

In [68]:
for dfa in dfs:
  dfa.rename(columns={'Finish time':'Time'}, inplace=True)
  dfa.rename(columns={'FINISH':'Time'}, inplace=True)
  dfa.rename(columns={'Finish':'Time'}, inplace=True)

In [69]:
for df in dfs:
  df['Seconds'] = pd.to_timedelta(df['Time']).dt.total_seconds().astype(int)

In [70]:
for df in dfs:
  print(df.head(3))

   Overall Place  BIB Division     Time Last Name First Name Country  Year  \
0             69  426    18-39  2:33:28    Duncan     Nicola     IRL  2014
1            191  374    18-39  2:39:43   Briscoe      Julie     GBR  2014
2            197  521    18-39  2:39:55      Bird       Sara     GBR  2014

  Gender  Seconds
0      F     9208
1      F     9583
2      F     9595
   Overall Place   BIB Division     Time Last Name First Name Country  Year  \
0              1   943    18-39  2:16:27       Way     Steven     GBR  2014
1              2   851    18-39  2:16:46   Gilbert       John     GBR  2014
2              3  1043    18-39  2:19:59    Pepper        Jon     GBR  2014

  Gender  Seconds
0      M     8187
1      M     8206
2      M     8399
   Overall Place    BIB Division     Time  Last Name First Name Country  Year  \
0            203  25371    40-44  2:36:55  Radcliffe      Paula     GBR  2015
1            220    417    18-39  2:37:24   Connolly     Breege     GBR  2015
2            225    379    18-39  2:37:35      Spink      Jenny     GBR  2015

  Gender  Seconds
0      F     9415
1      F     9444
2      F     9455
   Overall Place   BIB Division     Time Last Name First Name Country  Year  \
0              1  1147    18-39  2:15:51   Kimpton        Ian     GBR  2015
1              2   910    18-39  2:18:12   Gilbert       John     GBR  2015
2              3  1252    18-39  2:20:45     Scott      Aaron     GBR  2015

  Gender  Seconds
0      M     8151
1      M     8292
2      M     8445
   Overall Place  BIB Division     Time Last Name First Name Country  Year  \
0            125  289    18-39  2:33:20    Barlow      Tracy     GBR  2016
1            214  645    18-39  2:37:35      Muir       Tina     GBR  2016
2            228  494    18-39  2:38:04      Munn     Hayley     GBR  2016

  Gender  Seconds
0      F     9200
1      F     9455
2      F     9484
   Overall Place   BIB Division     Time    Last Name First Name Country  \
0              1  1000    18-39  2:17:20        Hehir       Sean     IRL
1              2  1288    18-39  2:17:26  Martelletti       Paul     GBR
2              3  1316    18-39  2:19:17       Frazer     Thomas     IRL

   Year Gender  Seconds
0  2016      M     8240
1  2016      M     8246
2  2016      M     8357
   Overall Place  BIB Division     Time Last Name First Name Country  Year  \
0            201  666    18-39  2:37:07  Boniface       Anna     GBR  2017
1            287  823    18-39  2:39:11  Clements        Amy     GBR  2017
2            298  715    18-39  2:39:27     Davis      Julia     GBR  2017

  Gender  Seconds
0      F     9427
1      F     9551
2      F     9567
   Overall Place   BIB Division     Time  Last Name First Name Country  Year  \
0              1  1154    18-39  2:14:49  Griffiths       Josh     GBR  2017
1              2  1454    18-39  2:16:18      Hehir       Sean     GBR  2017
2              3  1825    18-39  2:17:45      Sharp       Matt     GBR  2017

  Gender  Seconds
0      M     8089
1      M     8178
2      M     8265
   Overall Place  BIB Division     Time Last Name First Name Country  Year  \
0            271  970    18-39  2:44:50    Porter    Georgia     USA  2018
1            294  619    18-39  2:46:27   Oldroyd     Hannah     GBR  2018
2            297  849    18-39  2:46:36    Bowman      Laura     USA  2018

  Gender  Seconds
0      F     9890
1      F     9987
2      F     9996
   Overall Place   BIB Division     Time Last Name First Name Country  Year  \
0              1  2007    18-39  2:19:40    Wallis     Daniel     GBR  2018
1              2  1436    18-39  2:20:19   Gilbert       John     GBR  2018
2              3  1319    40-44  2:21:14  O'Hanlon       Gary     IRL  2018

  Gender  Seconds
0      M     8380
1      M     8419
2      M     8474

In [71]:
new_column_order = [
    'Last Name', 'First Name', 'Division', 'Country', 'BIB', 'Overall Place',
    'Time', 'Seconds', 'Year', 'Gender'
]

for i in range(len(dfs)):
    dfs[i] = dfs[i][new_column_order]

In [72]:
combined_df = pd.concat(dfs)

In [73]:
new_column_order = [
    'Last Name', 'First Name', 'Division', 'Country', 'BIB', 'Overall Place',
    'Time', 'Seconds', 'Year', 'Gender'
]

combined_df = combined_df[new_column_order]
combined_df

,Last Name,First Name,Division,Country,BIB,Overall Place,Time,Seconds,Year,Gender
0,Duncan,Nicola,18-39,IRL,426,69,2:33:28,9208,2014,F
1,Briscoe,Julie,18-39,GBR,374,191,2:39:43,9583,2014,F
2,Bird,Sara,18-39,GBR,521,197,2:39:55,9595,2014,F
3,Munn,Hayley,18-39,GBR,273,208,2:40:35,9635,2014,F
4,Fletcher,Shona,18-39,GBR,410,370,2:44:59,9899,2014,F
...,...,...,...,...,...,...,...,...,...,...
95,Hogben,Peter,18-39,GBR,1452,96,2:37:17,9437,2018,M
96,Fiz,Martin,55-59,ESP,1994,97,2:37:22,9442,2018,M
97,Compton,Che,40-44,GBR,1216,98,2:37:31,9451,2018,M
98,Foster,Thomas,18-39,GBR,1754,99,2:37:32,9452,2018,M
99,Dickinson,Matthew,18-39,GBR,1229,100,2:37:33,9453,2018,M

In [74]:
df2019f = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/london_data/London_Marathon_F2019.csv")
df2019m = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/london_data/London_Marathon_M2019.csv")
df2020f = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/london_data/London_Marathon_F2020.csv")
df2020m = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/london_data/London_Marathon_M2020.csv")
df2021f = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/london_data/London_Marathon_F2021.csv")
df2021m = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/london_data/London_Marathon_M2021.csv")
df2022f = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/london_data/London_Marathon_F2022.csv")
df2022m = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/london_data/London_Marathon_M2022.csv")
df2023f = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/london_data/London_Marathon_F2023.csv")
df2023m = pd.read_csv("https://raw.githubusercontent.com/snwnkang/CS171_Final_vis_Marathon/main/data/london_data/London_Marathon_M2023.csv")

In [75]:
dfsnewer = [df2019f, df2019m, df2020f, df2020m, df2021f, df2021m, df2022f, df2022m, df2023f, df2023m]

In [76]:
combined_df2 = pd.concat(dfsnewer)
combined_df2

,Unnamed: 0,Last Name,First Name,Division,Country,BIB,Overall Place,Time,Seconds,Year,Gender
0,0,Larsson,Mikaela,18-39,SWE,916,114,02:31:32,9092,2019,F
1,1,Davis,Stephanie,18-39,GBR,560,138,02:32:38,9158,2019,F
2,2,Roman-Duval,Julia,18-39,FRA,919,273,02:37:15,9435,2019,F
3,3,Gyurko,Fanni,18-39,HUN,566,344,02:38:47,9527,2019,F
4,4,Basil,Rochelle,18-39,NZL,915,371,02:39:07,9547,2019,F
...,...,...,...,...,...,...,...,...,...,...,...
95,95,Hendrix,Austin,18-39,USA,6083,96,02:28:39,8919,2023,M
96,96,Harradence,Oliver,40-44,GBR,1594,97,02:28:42,8922,2023,M
97,97,Poole,Jonathan,40-44,GBR,1824,98,02:28:45,8925,2023,M
98,98,Hurrell,James,18-39,GBR,1875,99,02:28:48,8928,2023,M
99,99,Horman,James,40-44,GBR,1409,100,02:28:49,8929,2023,M

In [77]:
df_all = [combined_df, combined_df2]
combined_df = pd.concat(df_all)

In [78]:
combined_df

,Last Name,First Name,Division,Country,BIB,Overall Place,Time,Seconds,Year,Gender,Unnamed: 0
0,Duncan,Nicola,18-39,IRL,426,69,2:33:28,9208,2014,F,NaN
1,Briscoe,Julie,18-39,GBR,374,191,2:39:43,9583,2014,F,NaN
2,Bird,Sara,18-39,GBR,521,197,2:39:55,9595,2014,F,NaN
3,Munn,Hayley,18-39,GBR,273,208,2:40:35,9635,2014,F,NaN
4,Fletcher,Shona,18-39,GBR,410,370,2:44:59,9899,2014,F,NaN
...,...,...,...,...,...,...,...,...,...,...,...
95,Hendrix,Austin,18-39,USA,6083,96,02:28:39,8919,2023,M,95.0
96,Harradence,Oliver,40-44,GBR,1594,97,02:28:42,8922,2023,M,96.0
97,Poole,Jonathan,40-44,GBR,1824,98,02:28:45,8925,2023,M,97.0
98,Hurrell,James,18-39,GBR,1875,99,02:28:48,8928,2023,M,98.0
99,Horman,James,40-44,GBR,1409,100,02:28:49,8929,2023,M,99.0

In [79]:
combined_df[-5:]

,Last Name,First Name,Division,Country,BIB,Overall Place,Time,Seconds,Year,Gender,Unnamed: 0
95,Hendrix,Austin,18-39,USA,6083,96,02:28:39,8919,2023,M,95.0
96,Harradence,Oliver,40-44,GBR,1594,97,02:28:42,8922,2023,M,96.0
97,Poole,Jonathan,40-44,GBR,1824,98,02:28:45,8925,2023,M,97.0
98,Hurrell,James,18-39,GBR,1875,99,02:28:48,8928,2023,M,98.0
99,Horman,James,40-44,GBR,1409,100,02:28:49,8929,2023,M,99.0

In [80]:
combined_df.drop('Unnamed: 0', axis=1, inplace=True)

In [81]:
combined_df

,Last Name,First Name,Division,Country,BIB,Overall Place,Time,Seconds,Year,Gender
0,Duncan,Nicola,18-39,IRL,426,69,2:33:28,9208,2014,F
1,Briscoe,Julie,18-39,GBR,374,191,2:39:43,9583,2014,F
2,Bird,Sara,18-39,GBR,521,197,2:39:55,9595,2014,F
3,Munn,Hayley,18-39,GBR,273,208,2:40:35,9635,2014,F
4,Fletcher,Shona,18-39,GBR,410,370,2:44:59,9899,2014,F
...,...,...,...,...,...,...,...,...,...,...
95,Hendrix,Austin,18-39,USA,6083,96,02:28:39,8919,2023,M
96,Harradence,Oliver,40-44,GBR,1594,97,02:28:42,8922,2023,M
97,Poole,Jonathan,40-44,GBR,1824,98,02:28:45,8925,2023,M
98,Hurrell,James,18-39,GBR,1875,99,02:28:48,8928,2023,M
99,Horman,James,40-44,GBR,1409,100,02:28:49,8929,2023,M

In [82]:
missing_values_count = combined_df.isnull().sum()
missing_values_count

Last Name        0
First Name       0
Division         2
Country          1
BIB              0
Overall Place    0
Time             0
Seconds          0
Year             0
Gender           0
dtype: int64

In [83]:
combined_df.to_csv("London_Marathon2014-2023.csv")